defmodule Webapp.Schema.Types.Permissions do
  use Absinthe.Schema.Notation

  @desc "Permissions"
  object :permissions do
    field :can_access_integration, :string
    field :can_create_project_dashboard, :string
    field :can_export_dashboard, :string
    field :can_manage_comment, :string
    field :can_execute, :string
    field :can_init_data, :string
    field :can_manage_integration, :string
    field :can_create_execution_context, :string
    field :can_manage_folder, :string
    field :can_invite_user_to_project, :string
    field :can_create_domain, :string
    field :can_create_table_data_load, :string
    field :can_see_other_user_details, :string
    field :can_manage_a_c_l, :string
    field :can_create_role, :string
    field :can_create_project_templates, :string
    field :can_create_help, :string
    field :can_manage_domain, :string
    field :can_manage_attribute_label, :string
    field :can_create_column, :string
    field :can_manage_report, :string
    field :can_export_report, :string
    field :can_manage_data_set, :string
    field :can_set_user_variables, :string
    field :can_create_attribute_group, :string
    field :can_set_style, :string
    field :can_validate_project, :string
    field :can_maintain_project, :string
    field :can_create_e_t_l_file, :string
    field :can_create_scheduled_mail, :string
    field :can_suspend_user_from_project, :string
    field :can_manage_is_production, :string
    field :can_maintain_user_filter_relation, :string
    field :can_manage_attribute, :string
    field :can_manage_report_definition, :string
    field :can_create_report, :string
    field :can_maintain_user_filter, :string
    field :can_set_locale, :string
    field :can_enrich_data, :string
    field :can_upload_non_production_c_s_v, :string
    field :can_manage_e_t_l_file, :string
    field :can_create_comment, :string
    field :can_create_data_set, :string
    field :can_manage_execution_context, :string
    field :can_create_table, :string
    field :can_manage_table_data_load, :string
    field :can_create_metric, :string
    field :can_refresh_data, :string
    field :can_manage_filter_settings, :string
    field :can_manage_project_dashboard, :string
    field :can_manage_project, :string
    field :can_manage_prompt, :string
    field :can_access_workbench, :string
    field :can_create_attribute_label, :string
    field :can_manage_column, :string
    field :can_create_prompt, :string
    field :can_manage_public_access_code, :string
    field :can_list_users_in_project, :string
    field :can_manage_attribute_group, :string
    field :can_manage_metric, :string
    field :can_manage_help, :string
    field :can_manage_table, :string
    field :can_set_project_variables, :string
    field :can_manage_fact, :string
    field :can_create_folder, :string
    field :can_manage_scheduled_mail, :string
    field :can_list_invitations_in_project, :string
    field :can_create_filter_settings, :string
    field :can_execute_raw, :string
    field :can_see_public_access_code, :string
    field :can_create_report_definition, :string
    field :can_create_fact, :string
    field :can_create_attribute, :string
    field :can_assign_user_with_role, :string
  end
end
